title: קהילה+
description: מדריך עסקים ובעלי מקצוע בקהילה
baseurl: "/community-plus"
url: "https://mmaxiw.github.io"
lang: he

collections:
  businesses:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: businesses
    values:
      layout: business

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore
